services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: unless-stopped
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: unless-stopped
    ports:
      - "9000"
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
  
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: unless-stopped
    ports:
      - "3306"
    networks:
      - inception
    volumes:
      - mariadb:/database

networks:
  inception:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/inception/data/wp
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/inception/data/db