http {
	# Configuring log files
	access_log /var/log/nginx/access.log;
	error_log  /var/log/nginx/error.log;

	# Importing some Headers
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	server {
		# Proxy http server
		# Only here to redirect to https
		listen 80;
		server_name default_server;
		
		# Only directive
		location / {
			return 301 https://$host$request_uri;
		}
	}

	server {
		# Main server on port 443 using ssl
    listen 443 ssl;
    server_name localhost _;

		# Include our SSL configuration
		include /etc/nginx/ssl-params.conf;

    location / {
        return 200 "HTTPS nginx works\n";
        add_header Content-Type text/plain;
    }
	}
}