events {
	worker_connections 1024;
}

http {
	# Configuring log files
	access_log /var/log/nginx/access.log;
	error_log  /var/log/nginx/error.log;

	# Importing some headers
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	server {
		# Proxy http server
		# Only here to redirect to https
		listen 80;
		server_name localhost nitadros.42.fr;
		
		# Only directive
		location / {
			return 301 https://$host$request_uri;
		}
	}

	server {
		# Main server on port 443 using ssl
    listen 443 ssl;
    server_name localhost nitadros.42.fr;

		root /var/www/html;
		index index.php;
		
		# Include our SSL configuration
		include /etc/nginx/ssl-params.conf;

    location / {
			try_files $uri $uri/ /index.php;
		}

		# Redirect all php file requests to wordpress container
		location ~ \.php$ {
			include fastcgi_params;
			fastcgi_pass wordpress:9000;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		}
	}
}